### ISSUE TITLE
Compatibility with CUDA 12

### ISSUE THREAD

**Issue by 36000** [dipy/GPUStreamlines#15]
Other than updating the FROM line in the Dockerfile, what changes would be necessary to update this code to CUDA 12?

**Comment by mauro-bis** [comment]
What problems are you having exactly with CUDA 12?

**Comment by 36000** [comment]
I was able to get this to work with CUDA 12 by simply changing the FROM line in the Dockerfile to 12.0.1-devel-ubuntu20.04 . I ran into some other issue but it turns out that had nothing to do with GPUStreamlines. Closing this issue, thanks!
